/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 16
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 14
#define ALIAS_COUNT 0
#define TOKEN_COUNT 7
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_ATbdiagram = 1,
  anon_sym_LF = 2,
  anon_sym_ATend = 3,
  sym_diagram_indent = 4,
  sym_diagram_char = 5,
  sym_other = 6,
  sym_source_file = 7,
  sym__block = 8,
  sym_bdiagram_block = 9,
  sym_diagram_line = 10,
  aux_sym_source_file_repeat1 = 11,
  aux_sym_bdiagram_block_repeat1 = 12,
  aux_sym_diagram_line_repeat1 = 13,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_ATbdiagram] = "@bdiagram",
  [anon_sym_LF] = "\n",
  [anon_sym_ATend] = "@end",
  [sym_diagram_indent] = "diagram_indent",
  [sym_diagram_char] = "diagram_char",
  [sym_other] = "other",
  [sym_source_file] = "source_file",
  [sym__block] = "_block",
  [sym_bdiagram_block] = "bdiagram_block",
  [sym_diagram_line] = "diagram_line",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_bdiagram_block_repeat1] = "bdiagram_block_repeat1",
  [aux_sym_diagram_line_repeat1] = "diagram_line_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_ATbdiagram] = anon_sym_ATbdiagram,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_ATend] = anon_sym_ATend,
  [sym_diagram_indent] = sym_diagram_indent,
  [sym_diagram_char] = sym_diagram_char,
  [sym_other] = sym_other,
  [sym_source_file] = sym_source_file,
  [sym__block] = sym__block,
  [sym_bdiagram_block] = sym_bdiagram_block,
  [sym_diagram_line] = sym_diagram_line,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_bdiagram_block_repeat1] = aux_sym_bdiagram_block_repeat1,
  [aux_sym_diagram_line_repeat1] = aux_sym_diagram_line_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_ATbdiagram] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATend] = {
    .visible = true,
    .named = false,
  },
  [sym_diagram_indent] = {
    .visible = true,
    .named = true,
  },
  [sym_diagram_char] = {
    .visible = true,
    .named = true,
  },
  [sym_other] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_bdiagram_block] = {
    .visible = true,
    .named = true,
  },
  [sym_diagram_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bdiagram_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_diagram_line_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      if (lookahead == '@') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == ' ') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(1);
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(24);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(23);
      if (lookahead == '@') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(3);
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(24);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(4);
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(24);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(5);
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(24);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 8:
      if (lookahead == 'b') ADVANCE(9);
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == 'g') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(6);
      END_STATE();
    case 13:
      if (lookahead == 'm') ADVANCE(18);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 15:
      if (lookahead == 'r') ADVANCE(7);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') SKIP(16);
      if (lookahead == '@') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_ATbdiagram);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_ATbdiagram);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == ' ') ADVANCE(25);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_ATend);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_diagram_indent);
      if (lookahead == ' ') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_diagram_char);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_diagram_char);
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == ' ') ADVANCE(25);
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(24);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_diagram_char);
      if (lookahead == ' ') ADVANCE(26);
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(24);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_diagram_char);
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == '@') ADVANCE(31);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(37);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == 'a') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == 'a') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == 'b') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == 'd') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == 'g') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == 'i') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == 'm') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == 'r') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_other);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 16},
  [2] = {.lex_state = 16},
  [3] = {.lex_state = 16},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 16},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_ATbdiagram] = ACTIONS(1),
    [anon_sym_ATend] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(15),
    [sym__block] = STATE(2),
    [sym_bdiagram_block] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_ATbdiagram] = ACTIONS(5),
    [sym_other] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(5), 1,
      anon_sym_ATbdiagram,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      sym_other,
    STATE(3), 3,
      sym__block,
      sym_bdiagram_block,
      aux_sym_source_file_repeat1,
  [15] = 4,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      anon_sym_ATbdiagram,
    ACTIONS(18), 1,
      sym_other,
    STATE(3), 3,
      sym__block,
      sym_bdiagram_block,
      aux_sym_source_file_repeat1,
  [30] = 5,
    ACTIONS(21), 1,
      anon_sym_ATend,
    ACTIONS(23), 1,
      sym_diagram_indent,
    ACTIONS(25), 1,
      sym_diagram_char,
    STATE(7), 1,
      aux_sym_diagram_line_repeat1,
    STATE(5), 2,
      sym_diagram_line,
      aux_sym_bdiagram_block_repeat1,
  [47] = 5,
    ACTIONS(27), 1,
      anon_sym_ATend,
    ACTIONS(29), 1,
      sym_diagram_indent,
    ACTIONS(32), 1,
      sym_diagram_char,
    STATE(7), 1,
      aux_sym_diagram_line_repeat1,
    STATE(5), 2,
      sym_diagram_line,
      aux_sym_bdiagram_block_repeat1,
  [64] = 4,
    ACTIONS(23), 1,
      sym_diagram_indent,
    ACTIONS(25), 1,
      sym_diagram_char,
    STATE(7), 1,
      aux_sym_diagram_line_repeat1,
    STATE(4), 2,
      sym_diagram_line,
      aux_sym_bdiagram_block_repeat1,
  [78] = 3,
    ACTIONS(35), 1,
      anon_sym_LF,
    ACTIONS(37), 1,
      sym_diagram_char,
    STATE(11), 1,
      aux_sym_diagram_line_repeat1,
  [88] = 3,
    ACTIONS(37), 1,
      sym_diagram_char,
    ACTIONS(39), 1,
      anon_sym_LF,
    STATE(11), 1,
      aux_sym_diagram_line_repeat1,
  [98] = 2,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 2,
      anon_sym_ATbdiagram,
      sym_other,
  [106] = 1,
    ACTIONS(45), 3,
      anon_sym_ATend,
      sym_diagram_indent,
      sym_diagram_char,
  [112] = 3,
    ACTIONS(47), 1,
      anon_sym_LF,
    ACTIONS(49), 1,
      sym_diagram_char,
    STATE(11), 1,
      aux_sym_diagram_line_repeat1,
  [122] = 1,
    ACTIONS(52), 3,
      anon_sym_ATend,
      sym_diagram_indent,
      sym_diagram_char,
  [128] = 2,
    ACTIONS(54), 1,
      sym_diagram_char,
    STATE(8), 1,
      aux_sym_diagram_line_repeat1,
  [135] = 1,
    ACTIONS(56), 1,
      anon_sym_LF,
  [139] = 1,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 15,
  [SMALL_STATE(4)] = 30,
  [SMALL_STATE(5)] = 47,
  [SMALL_STATE(6)] = 64,
  [SMALL_STATE(7)] = 78,
  [SMALL_STATE(8)] = 88,
  [SMALL_STATE(9)] = 98,
  [SMALL_STATE(10)] = 106,
  [SMALL_STATE(11)] = 112,
  [SMALL_STATE(12)] = 122,
  [SMALL_STATE(13)] = 128,
  [SMALL_STATE(14)] = 135,
  [SMALL_STATE(15)] = 139,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [18] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_bdiagram_block_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_bdiagram_block_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_bdiagram_block_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bdiagram_block, 4, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bdiagram_block, 4, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_diagram_line, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_diagram_line_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_diagram_line_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_diagram_line, 3, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [58] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_bdiagram(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "bdiagram",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
